name: Publish features
on:
  # push:
  #   branches: "main"
  #   paths:
  #     - src/*/**
  #     - .github/workflows/publish-features.yml
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  list-features:
    outputs:
      all-features: ${{ steps.list-features.outputs.all-features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: list-features
        uses: devcontainers-community/list-features@v2
  publish-feature:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.list-features.outputs.all-features) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @devcontainers/cli
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers-community/publish-feature@v1
        with:
          path: src/${{ matrix.id }}
  update-readme:
    needs: publish-features
    permissions:
      contents: write
    uses: ./.github/workflows/update-readme.yml
    secrets: inherit
